### Get All MBTA Routes
GET http://localhost:8081/routes/mbta-routes HTTP/1.1

###

### Retrieve MBTA Lines with Valid Filters

# Green Line (Filtered by Route ID)
GET http://localhost:8081/routes/mbta-routes?id=Green HTTP/1.1

###

# Red Line (Filtered by Route ID)
GET http://localhost:8081/routes/mbta-routes?id=Red HTTP/1.1

###

# Blue Line (Filtered by Type - Subway)
GET http://localhost:8081/routes/mbta-routes?type=1 HTTP/1.1

###

# Bus Routes (Filtered by Type)
GET http://localhost:8081/routes/mbta-routes?type=3 HTTP/1.1

###

# Routes Passing Through North Station (Stop Filter)
GET http://localhost:8081/routes/mbta-routes?stop=place-north HTTP/1.1

###

# Inbound Routes Only (Direction ID Filter)
GET http://localhost:8081/routes/mbta-routes?direction_id=1 HTTP/1.1
