### Get All Subway Lines
GET http://localhost:8081/api/lines

###

### Get All Stations for Red Line
GET http://localhost:8081/api/stations/Red

###

### Get Arrivals at Park Street (All Directions)
GET http://localhost:8081/api/arrivals/place-pktrm

###

### Get Arrivals at Park Street (Inbound Only)
GET http://localhost:8081/api/arrivals/place-pktrm?direction=0

###

### Get Arrivals at Park Street (Outbound Only)
GET http://localhost:8081/api/arrivals/place-pktrm?direction=1
