### Signup (Create User)
POST http://localhost:8081/api/users/signup
Content-Type: application/json

{
  "name":  "Kutmanbek2",
  "lastname":  "Salaiev",
  "username": "ksaiev",
  "email": "ksalaiev@gil.com",
  "password": "AliNurali8587$$"
}



### Login (Authenticate User)
POST http://localhost:8081/api/users/login
Content-Type: application/json

{
  "username":  "ksalaiev",
  "password":"AliNurali8587$$"
}

###

### Get All Users
GET http://localhost:8081/api/users/getAll

###

### Get User by ID (replace :id)
GET http://localhost:8081/api/users/getUserById/REPLACE_WITH_USER_ID

###

### Delete User by ID
DELETE http://localhost:8081/api/users/deleteUser/REPLACE_WITH_USER_ID

###

### Delete All Users
DELETE http://localhost:8081/api/users/deleteAll

###

### Create Favorite Route
POST http://localhost:8081/api/favorite-routes
Content-Type: application/json

{
  "userId": "REPLACE_WITH_USER_ID",
  "fromStation": "place-sstat",
  "toStation": "place-north",
  "routeName": "Red Line"
}

###

### Get All Favorite Routes for a User
GET http://localhost:8081/api/favorite-routes/REPLACE_WITH_USER_ID

###

### Update Favorite Route by Route ID
PUT http://localhost:8081/api/favorite-routes/REPLACE_WITH_ROUTE_ID
Content-Type: application/json

{
  "fromStation": "place-savin",
  "toStation": "place-ashmt",
  "routeName": "Updated Red Line"
}

###


