### Signup (Create User)
POST http://localhost:8081/api/users/signup
Content-Type: application/json

{
  "name":  "Kutmanbek2",
  "lastname":  "Salaiev",
  "username": "ksaiev",
  "email": "ksalaiev@gil.com",
  "password": "AliNurali8587$$"
}


### Login (Authenticate User)
POST http://localhost:8081/api/users/login
Content-Type: application/json

{
  "username":  "ksalaiev",
  "password":"AliNurali8587$$"
}

### ✅ Update User By ID (like getUserById)
PUT http://localhost:8081/api/users/updateUserById/68118ac5ea23c2fbe4e28aa6
Content-Type: application/json

{
  "name": "Kutmanbek",
  "lastname": "Salaiev",
  "email": "ksalaiev@gmail.com",
  "password": "Pulisic22$$"
}

### Get All Users
GET http://localhost:8081/api/users/getAll

###

### Get User by ID 
GET http://localhost:8081/api/users/getUserById/68118ac5ea23c2fbe4e28aa6

###

### Delete User by ID
DELETE http://localhost:8081/api/users/deleteUser/680bb5fd4b8ebf8b036b791a

###

### Delete All Users
DELETE http://localhost:8081/api/users/deleteAll

###

### ➡️ Add Favorite Route
POST http://localhost:8081/api/favorite-routes/68118ac5ea23c2fbe4e28aa6
Content-Type: application/json

{
  "fromStation": "South Station",
  "toStation": "Alewife",
  "routeName": "Morning Commute"
}

###  Get All Favorite Routes
GET http://localhost:8081/api/favorite-routes/68118ac5ea23c2fbe4e28aa6

### Update a Favorite Route
PUT http://localhost:8081/api/favorite-routes/68118ac5ea23c2fbe4e28aa6/6811aa826af013e16b468cd0
Content-Type: application/json

{
  "fromStation": "Alewife",
  "toStation": "South Station",
  "routeName": "Evening Return"
}


###  Delete a Favorite Route
DELETE http://localhost:8081/api/favorite-routes/680b8f912c4066dd293e9359/680f7a03496480b3f805d3bd










### Create Post
POST http://localhost:8081/api/feedback/createPost/feedback
Content-Type: application/json

{
  "username": "testuser",
  "comment": "blank",
  "station": "wonderland"
}

###  Get Post
GET http://localhost:8081/api/feedback/getPost/feedback/

###  Update Post
PUT http://localhost:8081/api/feedback/updatePost/feedback/680bbc6111b0dc54809fa1b5
Content-Type: application/json

{
  "username": "newTest",
  "comment": "nada",
  "station": "Wood island"
}

###  Delete Post
DELETE http://localhost:8081/api/feedback/deletePost/feedback/


